pipeline {
   agent any
   stages {
        stage('Build'){
            steps{
                script {
                    dir("OminChannelConsumerService"){
                        docker.build("omi/ep-consumer-service:${env.BUILD_ID}")
                        docker.build("omi/ep-consumer-service:latest")
                    }
                }
            }
        }
    }
}