pipeline {
   agent any
   stages {
       stage('Copy config') {
           steps {
                   configFileProvider([
                               configFile(fileId: 'frontend-env',
                               targetLocation: 'frontend/.env')
                               ]) {}
               }
           }
        stage('Build'){
            steps{
                script {
                    dir("frontend"){
                        docker.build("smileup/affiliate-frontend:${env.BUILD_ID}")
                        docker.build("smileup/affiliate-frontend:latest")
                    }
                }
            }
        }
    }
}